CodeNews/Controllers/YouLostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ThanhNienNews.Controllers
{
    public class YouLostController : Controller
    {
        //
        // GET: /YouLost/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult BaoMatDo()
        {

            return View();
        }
    }
}

CodeNews/Views/YouLost/BaoMatDo.cshtml
@{
    ViewBag.Title = "BaoMatDo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BaoMatDo</h2>

CodeNews/Views/YouLost/Create.cshtml
@model ThanhNienNews.Models.YouLost
@using ThanhNienNews.Controllers
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/Site.css")" rel="Stylesheet" type="text/css" />
<link rel="stylesheet" href="@Url.Content("~/Content/validationEngine.jquery.css")" type="text/css" />
<link href="@Url.Content("~/Content/jquery.fileupload-ui.css")" rel="stylesheet" type="text/css" />

<script src="@Url.Content("~/Scripts/jquery.validationEngine-en.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.min.js")" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/vendor/jquery.ui.widget.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.iframe-transport.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.fileupload.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/car.js")" type="text/javascript"></script>
<div class="entry">
         
                    	 <div style="border-top:1px dotted #D1D1D1"></div> 
               <div align="center" id="settyper">Chọn kiểu gõ   <input type="radio" onclick="return Mudim.SetMethod(4);" name="typer" value="1"> Tự động   <input type="radio" onclick="return  Mudim.SetMethod(2);" name="typer" value="0"> Telex   <input type="radio" onclick="return  Mudim.SetMethod(1);" name="typer" value="0"> VNI   <input type="radio" onclick="return Mudim.SetMethod(0);" name="typer" value="0" checked=""> Tắt</div> 
             	 <div style="border-top:1px dotted #D1D1D1"></div>
  @using (Html.BeginForm("Create", "YouLost", FormMethod.Post, new { id = "youLostForm" }))
  {
   
   <div><input id="LostId" class="text-box single-line" type="text" value="" name="LostId" />
       @Html.TextBoxFor(model => model.DesShort, new { id = "txtDesShort", @class = "validate[required],textfield", @maxLength = 50, @style = "font-size:X-Large;height:30px;width:323px;", @tumlum = "aa" })
          
          <br /><input id="btnSave" type="button" value="Gui" />
     
                          <br /><input id="btnLoad" type="button" value="Load" />                            
     </div>                     
         
  }
                     
                  
     
        	

			</div>

CodeNews/Views/YouLost/Index.cshtml
@using ThanhNienNews.Models
@using ThanhNienNews.Helpers
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
trang chu